name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main    # or your default branch

permissions:
  contents: read    # for checkout
  pages: write      # to publish
  id-token: write   # for OIDC

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd project
          npm ci

      - name: Build with Vite
        run: |
          cd project
          npm run build

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: project/dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
