name: Build & Deploy Vite Site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read     # for checkout
  pages: write       # to publish
  id-token: write    # for OIDC

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd project
          npm ci

      - name: Build site
        run: |
          cd project
          npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: project/dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
