# File: .github/workflows/deploy.yml
name: Build & Publish to gh-pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: project
        run: npm install --no-audit --no-fund

      - name: Build
        working-directory: project
        run: |
          npm run build
          cp dist/index.html dist/404.html
          # version stamp (for verification)
          TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "$TS" > dist/_version.txt
          # add harmless build meta (does NOT touch asset paths)
          awk -v ts="$TS" '
            BEGIN{inj=0}
            /<head[^>]*>/ && !inj { print; print "    <meta name=\"x-build\" content=\"" ts "\">"; inj=1; next }
            { print }
          ' dist/index.html > dist/.tmp && mv dist/.tmp dist/index.html
          # ensure custom domain
          echo "lawtontennisacademy.com" > dist/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: project/dist
          force_orphan: true
