name: Build & Publish to gh-pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write   # needed to push to gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Build from /project (your bolt.new structure)
      - name: Install deps
        working-directory: project
        run: npm install --no-audit --no-fund

      - name: Build
        working-directory: project
        run: |
          npm run build
          cp dist/index.html dist/404.html  # SPA fallback
          echo "lawtontennisacademy.com" > dist/CNAME  # keep custom domain

      # Publish dist/ to gh-pages branch (no Pages publisher needed)
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: project/dist
          force_orphan: true
