# File: .github/workflows/deploy.yml
name: Build & Deploy (GitHub Pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Required so Pages accepts the artifact
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: project
        run: npm install --no-audit --no-fund

      - name: Build
        working-directory: project
        run: |
          npm run build
          cp dist/index.html dist/404.html  # SPA fallback

      # Debug: prove the artifact exists and isn't empty
      - name: Show dist contents
        working-directory: project
        run: |
          echo "Dist tree:"
          ls -lah dist || true
          echo "Size:"
          du -sh dist || true

      # Upload the built site for Pages to publish
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: project/dist

  # Publish (no environment gate so nothing can block it)
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
