# .github/workflows/deploy-pages.yml
name: Deploy Vite Site to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read       # for checkout
  pages: write         # for deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Add CNAME for custom domain
        run: echo 'lawtontennisacademy.com' > dist/CNAME

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          branch: gh-pages
          folder: dist
