name: Deploy Vite Site to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read     # needed for checkout
  pages: write       # needed to push to gh-pages
  id-token: write    # needed by actions/deploy-pages to get an OIDC token

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: project
        run: npm ci

      - name: Build site
        working-directory: project
        run: npm run build

      - name: Add CNAME for custom domain
        run: echo 'lawtontennisacademy.com' > project/dist/CNAME

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: pages
          path: project/dist

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v1
