name: Build & Publish to GitHub Pages

on:
  push:
    branches:
      - main    # or change to your default branch

permissions:
  contents: write    # needed so the GH_TOKEN can push to gh-pages
  pages: write       # needed to publish Pages
  id-token: write    # harmless to include

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies & build
        run: |
          cd project
          npm ci
          npm run build

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./project/dist
          cname: lawtontennisacademy.com
